[package]
name = "fibonacci-sequencer"
version = "0.1.0"
authors = ["codedcosmos <codedcosmos.mail@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types = "0.9.0"